### ISSUE TITLE
No order history showing in the dashboard orders page

### ISSUE THREAD

**Issue by justinelut** [rigby-sh/solace-medusa-starter#94]
![Screenshot from 2024-10-28 16-37-41](https://github.com/user-attachments/assets/e35ab2ca-e922-4301-84d3-65ae4cd8c255)
 unfortunately even after trying to find any misconfigurations, order history does not seem to appear in the order history page.
i dont think the problem is medusa backend bcos the default medusa nextjs starter does not have that issue and order history is shown, 
![image](https://github.com/user-attachments/assets/41956679-0f49-46b6-bed9-f61bdec1119c)
https://next.medusajs.com, check this link

**Comment by agnwoj99** [comment]
@justinelut I understand, but when you put the starter locally, it still doesn’t work. As you can see, I’m logged in, place an order and it doesn’t show up in my account:
https://jam.dev/c/1b6c4da7-3401-4f76-9a92-443b7e1cd1e0

Intended `customer_id` attribute doesn't generate the order history at the moment and is being fixed by the Medusa team. Please follow [this issue](https://github.com/medusajs/medusa/issues/9755).
Also, I hope they solve this problem quickly 💪🏻

**Comment by justinelut** [comment]
@agnwoj99 thanks for the insight, I guess we will have to wait for the next update and hopefully they fix the issue.
